[phases.setup]
nixPkgs = ["nodejs_20", "caddy"]

[phases.install]
cmds = [
  "npm ci --prefer-offline --no-audit"
]

[phases.build]
cmds = [
  "npm run build"
]

[start]
cmd = "caddy file-server --root dist --listen :$PORT --browse"

[variables]
NODE_ENV = "production"