[phases.setup]
nixPkgs = ["dotnet-sdk_8", "sqlite"]

[phases.install]
cmds = [
  "dotnet restore --no-cache --verbosity minimal"
]

[phases.build]
cmds = [
  "dotnet publish -c Release -o out --no-restore --self-contained false --verbosity minimal"
]

[start]
cmd = "dotnet out/backend.dll --urls http://0.0.0.0:$PORT"

[variables]
DOTNET_ENVIRONMENT = "Production"
ASPNETCORE_ENVIRONMENT = "Production"
DOTNET_SYSTEM_GLOBALIZATION_INVARIANT = "false"
DOTNET_EnableDiagnostics = "0"