# PostgreSQL-only Docker Compose
# For local PostgreSQL deployment

services:
  postgres:
    image: postgres:16
    container_name: ${POSTGRES_CONTAINER_NAME:-garmin-challenge-postgres}
    environment:
      - POSTGRES_DB=${POSTGRES_DB:-garmin_challenge}
      - POSTGRES_USER=${POSTGRES_USER:-postgres}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-postgres}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "${POSTGRES_PORT:-5432}:5432"
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-postgres}"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 5s

volumes:
  postgres_data: